version : '3'

networks:
  laravel:

services:
  nginx:
    image : nginx:stable-alpine
    container_name : nginx_v2
    ports:
      - "80:80"
    volumes:
      - ./lottery:/var/www/html/lottery
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image : mysql:5.7.22
    container_name : mysql_v2
    restart : unless-stopped
    tty : true
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlinit:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABSE : test_v2
      MYSQL_USER : root
      MYSQL_ROOT_PASSWORD : root
      SERVICE_TAG : dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context : .
      dockerfile : Dockerfile
    container_name : php_v2
    volumes:
      - ./lottery:/var/www/html/lottery
      - ./.env:/var/www/html/lottery/.env
    ports:
      - "9000:9000"
    networks:
      - laravel

